name = "artists-portfolio"
compatibility_date = "2024-01-04"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
watch_dir = "src"

[build.upload]
format = "service-worker"

[site]
bucket = ".next/out"
entry-point = "src/app/_worker.js"

[env.production]
workers_dev = true 